# Permalinks
permalink:           pretty

# Setup
title:               Lin Mei
tagline:             Thinking on Data Science 
url:                 http://linmei.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lin Mei
  url:               
  email:             linmei99@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/linmei99

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
